library(ggplot2)
dat <- read.delim("./PCA.matrix", row.names = 1, header=TRUE,check.names=F,sep="\t")
pca <- prcomp(t(dat))
result <- as.data.frame(pca$x)
result$rep <- c("aac","aac(6')I1","aac(6')-Ib(aka aacA4)-2","aac(6')-Ib(aka aacA4)-3","aac(6')-II","aacA/aphD","aacC","aacC1","aacC2","aacC4","aadA-1","aadA-2","aadA1","aadA-1-1","aadA-1-2","aadA2-1","aadA2-2","aadA2-3","aadA5-1","aadA5-2","aadA9-1","aadA9-2","aadD","aadE","acrA-1","acrA-2","acrA-3","acrA-4","acrA-5","acrB-1","acrF","acrR-1","adeA","ampC-1","ampC-2","ampC-4","ampC-5","ampC-6","ampC-7","ampC-9","aph(2')-Id-1","aphA1(aka kanR)","bacA-1","bla1","blaCMY2-1","blaCMY2-2","blaCTX-M-1","blaCTX-M-2","blaCTX-M-4","blaCTX-M-5","blaCTX-M-6","bla-L1","blaMOX/blaCMY","blaOCH","blaOXY","blaPAO","blaROB","blaSFO","blaVIM","carB","ceoA","cmlA1-1","cmlA1-2","cmx(A)","cphA-1","cphA-2","dfrA1","emrD","erm(34)","erm(36)","ermA","ermB","ermC","ermF","ermT-1","ermT-2","ermY","fabK","floR","fox5","lnuA-1","lnuB-1","lnuB-2","marR-1","matA/mel","mdtE/yhiU","mefA","mepA","mexA","mexE","mexF","mphA-1","mphA-2","mphB","mtrC-1","mtrC-2","mtrD-2","mtrD-3","ndm-1","oleC","oprD","oprJ","pikR2","pncA","putitive multidrug","qacEdelta1-1","qacEdelta1-2","qacH-1","rarD-2","sat4","spcN-2","str","strA","strB","sul1","sul2","sulA/folP-3","tet(34)","tetA-2","tetD-2","tetG-1","tetG-2","tetL-2","tetM-1","tetM-2","tetO-1","tetPA","tetPB-1","tetPB-2","tetPB-3","tetPB-4","tetPB-5","tetQ","tetR-2","tetT","tetX","tolC-1","tolC-2","tolC-3","ttgA","ttgB","vanA","vanB-1","vanC-3","vanC2/vanC3","vanHB","vanHD","vanRA-1","vanRB","vanRC","vanSC-2","vanTC-1","vanTC-2","vanYD-1","vatE-1","vgb-1","yceL/mdtH-1","yceL/mdtH-3","yidY/mdtL-1")
xmax=max(result$PC1)*1.4
xmin=min(result$PC1)
##p <- ggplot(result) + geom_point(aes(x=result$PC1,y=result$PC2,color=result$rep)) + geom_text(aes(x=result$PC1, y=result$PC2, label=rownames(result),hjust=-0.65, color=result$rep,size=.5))
p <- ggplot(result) + geom_point(aes(x=result$PC1,y=result$PC2,color=result$rep)) + geom_text(aes(x=result$PC1, y=result$PC2, label=rownames(result),hjust=-0.05, color=result$rep),size=4)+xlim(xmin,xmax)
p <- p + theme_bw()
p <- p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
p <- p + theme(legend.title=element_blank()) + xlab("PC1") + ylab("PC2")
p <- p + theme(legend.position = "none")
pdf(file="out/PCA.pca.pdf")
print(p)
dev.off()
