library(ggplot2)
dat <- read.delim("./test.matrix", row.names = 1, header=TRUE,check.names=F,sep="\t")
pca <- prcomp(t(dat))
result <- as.data.frame(pca$x)
result$rep <- c("pelvic_incidence","pelvic_tilt numeric","lumbar_lordosis_angle","sacral_slope")
p <- ggplot(result) + geom_point(aes(x=result$PC1,y=result$PC2,color=result$rep)) + geom_text(aes(x=result$PC1, y=result$PC2-500, label=rownames(result), color=result$rep,size=.5))
p <- p + theme_bw()
p <- p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
p <- p + theme(legend.title=element_blank()) + xlab("PC1") + ylab("PC2")
p <- p + theme(legend.position = "none")
pdf(file="out/test.pca.pdf")
print(p)
dev.off()
