library(ggplot2)
dat <- read.delim("./aa.matrix", row.names = 1, header=TRUE,check.names=F,sep="\t")
pca <- prcomp(t(dat))
result <- as.data.frame(pca$x)
result$rep <- c("RPL41","EEF1A1","COX2","ND4","TPT1","RPL37A","RPS2","RPL39","ATP6","COX1","RPS18","RPS16","RPS4X","RPLP0","RPS15","RPL10A","RPL7","RPS10","RPS6","UBC","HUWE1","RPL9","UBB","RPS29","TMSB10","RPL14","RPS19","RPS12","GAPDH","ND2","ACTB","RPS7","RPL30","RPLP1")
xmax=max(result$PC1)*1.4
xmin=min(result$PC1)
##p <- ggplot(result) + geom_point(aes(x=result$PC1,y=result$PC2,color=result$rep)) + geom_text(aes(x=result$PC1, y=result$PC2, label=rownames(result),hjust=-0.65, color=result$rep,size=.5))
p <- ggplot(result) + geom_point(aes(x=result$PC1,y=result$PC2,color=result$rep)) + geom_text(aes(x=result$PC1, y=result$PC2, label=rownames(result),hjust=-0.05, color=result$rep),size=4)+xlim(xmin,xmax)
p <- p + theme_bw()
p <- p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
p <- p + theme(legend.title=element_blank()) + xlab("PC1") + ylab("PC2")
p <- p + theme(legend.position = "none")
pdf(file="out/aa.pca.pdf")
print(p)
dev.off()
